// Generated by gencpp from file puppy/HumanActionsResponse.msg
// DO NOT EDIT!


#ifndef PUPPY_MESSAGE_HUMANACTIONSRESPONSE_H
#define PUPPY_MESSAGE_HUMANACTIONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace puppy
{
template <class ContainerAllocator>
struct HumanActionsResponse_
{
  typedef HumanActionsResponse_<ContainerAllocator> Type;

  HumanActionsResponse_()
    : health_output(0)  {
    }
  HumanActionsResponse_(const ContainerAllocator& _alloc)
    : health_output(0)  {
  (void)_alloc;
    }



   typedef uint8_t _health_output_type;
  _health_output_type health_output;





  typedef boost::shared_ptr< ::puppy::HumanActionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::puppy::HumanActionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HumanActionsResponse_

typedef ::puppy::HumanActionsResponse_<std::allocator<void> > HumanActionsResponse;

typedef boost::shared_ptr< ::puppy::HumanActionsResponse > HumanActionsResponsePtr;
typedef boost::shared_ptr< ::puppy::HumanActionsResponse const> HumanActionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::puppy::HumanActionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::puppy::HumanActionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace puppy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'puppy': ['/home/houzy/dog_ws/src/puppy/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::puppy::HumanActionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy::HumanActionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puppy::HumanActionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puppy::HumanActionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy::HumanActionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy::HumanActionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::puppy::HumanActionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc338d3ec976ec833c191ffd03914443";
  }

  static const char* value(const ::puppy::HumanActionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc338d3ec976ec83ULL;
  static const uint64_t static_value2 = 0x3c191ffd03914443ULL;
};

template<class ContainerAllocator>
struct DataType< ::puppy::HumanActionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "puppy/HumanActionsResponse";
  }

  static const char* value(const ::puppy::HumanActionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::puppy::HumanActionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 health_output\n\
\n\
";
  }

  static const char* value(const ::puppy::HumanActionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::puppy::HumanActionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.health_output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanActionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::puppy::HumanActionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::puppy::HumanActionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "health_output: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.health_output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUPPY_MESSAGE_HUMANACTIONSRESPONSE_H
